[config]
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/waybar/scripts/launch.sh'

[templates.vscodium]
input_path = '~/.config/matugen/templates/vscodium-settings.json'
output_path = '/dev/null'
post_hook = '~/.config/matugen/hooks/vscodium.sh'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim.lua'
output_path = '~/.config/nvim/lua/colors.lua'
post_hook = ''

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
post_hook = ''
