set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-kitty:Tc" # true color support for kitty

set -g mouse on
set -sg escape-time 0
set -g history-limit 10000
set -g base-index 1 # window index starts at 1
set -g pane-base-index 1
set -g renumber-windows on

# reload this config without restarting tmux
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# vs code like behavior config:
bind - split-window -v -c "#{pane_current_path}"
bind t split-window -v -l 7 -c "#{pane_current_path}"

# open pane to the side
bind '\' split-window -h -c "#{pane_current_path}"

# open terminal, but at home
bind T split-window -v -l 15 -c "$HOME"

bind x kill-pane


# RESIZING

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# THEME; needs more attention
set -g status-style bg="#2e3440",fg="#d8dee9"
set -g status-left ""
set -g status-right "#[fg=#88c0d0]%H:%M "
set -g status-justify centre
setw -g window-status-current-style bg="#3b4252",fg="#eceff4",bold
