general {
    lock_cmd = hyprlock            # Your lockscreen command
    before_sleep_cmd = loginctl lock-session # Lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on # Turn displays on after sleep
}

# Example listener to lock the screen after 5 minutes
listener {
    timeout = 500                  # In seconds (5 minutes)
    on-timeout = ~/.config/hypr/scripts/video-playing.sh          # Command to run on timeout
}

# Example listener to turn off monitors after 10 minutes
listener {
    timeout = 600                  # In seconds (10 minutes)
    on-timeout = ~/.config/hypr/scripts/dpms-if-no-audio.sh
    on-resume = hyprctl dispatch dpms on
}
