[mgr]
cwd = { fg = "#88d6bb" }
find_keyword  = { fg = "#a8cbe2", bold = true }
find_position = { fg = "#b2ccc1", bg = "reset", bold = true }
marker_copied   = { fg = "#a8cbe2", bg = "#a8cbe2" }
marker_cut      = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_marked   = { fg = "#88d6bb", bg = "#88d6bb" }
marker_selected = { fg = "#b2ccc1", bg = "#b2ccc1" }
count_copied   = { fg = "#0d3446", bg = "#a8cbe2" }
border_symbol = "│"
border_style  = { fg = "#89938e" }
syntect_theme = "~/.config/yazi/tm-themes/Monokai Dark Soda.tmTheme"

[indicator]
parent = { fg = "#b2ccc1", bg="#12a16f"}
current = { fg = "#d9f2e9", bg="#009975", bold = true}

[tab]
active   = { fg = "#88d6bb", bg = "#00382b" }
inactive = { fg = "#b2ccc1", bg = "#1e352d" }

[mode]
normal_main = { fg = "#00382b", bg = "#41be93", bold = true }
normal_alt  = { fg = "#88d6bb", bg = "#738c7f" }

select_main = { fg = "#1e352d", bg = "#b2ccc1", bold = true }
select_alt  = { fg = "#b2ccc1", bg = "#1b211e" }

unset_main = { fg = "#0d3446", bg = "#a8cbe2", bold = true }
unset_alt  = { fg = "#a8cbe2", bg = "#1b211e" }

[status]

# Status bar background
bg = { bg = "#0f1512" }

# Individual status elements - these control the bottom bar text
style      = { fg = "#349875" }
size_style      = { fg = "#dee4df" }
date_style      = { fg = "#bfc9c3" }
sels_style      = { fg = "#88d6bb" }
separator_style = { fg = "#89938e" }

progress_label  = { bold = true }
progress_normal = { fg = "#88d6bb", bg = "#0f1512" }
progress_error  = { fg = "#ffb4ab", bg = "#0f1512" }


count_cut      = { fg = "#690005", bg = "#ffb4ab" }
count_selected = { fg = "#1e352d", bg = "#b2ccc1" }

hovered         = { fg = "#a3f2d6", bg = "#00513f" }
preview_hovered = { underline = true }
[input]
border   = { fg = "#88d6bb" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#88d6bb" }
active   = { fg = "#a8cbe2" }
inactive = {}

[tasks]
border  = { fg = "#88d6bb" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#0f1512" }
cand            = { fg = "#a8cbe2" }
rest            = { fg = "#89938e" }
desc            = { fg = "#88d6bb" }
separator_style = { fg = "#89938e" }

[help]
on      = { fg = "#a8cbe2" }
run     = { fg = "#b2ccc1" }
desc    = { fg = "#dee4df" }
hovered = { bg = "#1b211e", bold = true }
footer  = { fg = "#dee4df", bg = "#0f1512" }

[filetype]
rules = [
  { mime = "image/*", fg = "#a8cbe2" },
  { mime = "video/*", fg = "#88d6bb" },
  { mime = "audio/*", fg = "#b2ccc1" },
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },
]
