
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_shape

font_family JetBrains Mono
font_size   13

disable_ligature  no
enable_audio_bell no

shell             zsh
shell_integration disabled

cursor_shape                  beam
cursor_shape_unfocused        hollow
cursor_beam_thickness         1
cursor_blink_interval         0.5
cursor_stop_blinking_after    10
cursor_trail                  5
cursor_trail_decay            0.4     0.65
cursor_trail_start_threshold  2
cursor_trail_color #a0a0a0

scrollback_lines        2000
scrollbar               scrolled-and-hovered
scrollbar_interactive   yes
scrollbar_hover_width   0.7
scrollbar_gap           0.5

url_style               curly

remember_window_size    no

background_opacity      0.50

confirm_os_window_close 0

sync_to_monitor no

# Colors

foreground #979eab

color0 #282c34
color1 #e06c75
color2 #98c379
color3 #e5c07b
color4 #61afef
color5 #be5046
color6 #56b6c2
color7 #979eab
color8 #393e48
color9 #d19a66
color10 #56b6c2
color11 #e5c07b
color12 #61afef
color13 #be5046
color14 #56b6c2
color15 #abb2bf

# Tab Bar

active_tab_foreground   #282c34
active_tab_background   #979eab
inactive_tab_foreground #abb2bf
inactive_tab_background #282c34

initial_window_width 64c
initial_window_height 4c
remember_window_size no
